
apiVersion: v1
kind: Service

metadata:
  name: weather-forecast-service

spec:
  type: NodePort

  selector:
    app: weather-forecast

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
